services:
  - type: worker
    name: telegram-dropbox-bot
    env: python
    runtime: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    
